# secret_key_base: THERE WILL ALREADY BE SOME CRAZY STRING HERE. LEAVE IT THERE.
twilio_account_sid: AC5cf03725077534e446a53ef9fa60d006
twilio_auth_token: ef82d63e705092e8d82fea43ed15a659
twilio_phone_number: "+12019285612"

# client = Twilio::REST::Client.new
  # client.messages.create({ from: "+12019285612", to: '+19173406668', body: 'Hello there! This is a test'})
